name: Build for Windows
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Clone raylib source
        run: git clone https://github.com/raysan5/raylib.git

      - name: Install raylib
        run: cd raylib\src && make PLATFORM=PLATFORM_DESKTOP install

      - name: Create build directory and enter
        run: cd atari_breakout && mkdir build && cd build

      - name: Create cmake files
        run: cd atari_breakout\build && cmake .. && dir

      - name: Build
        run: cd atari_breakout\build && msbuild breakout.sln /property:Configuration=Release
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: atari_breakout\build\*