name: Build for Windows
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: For now, move to the first game directory
        run: cd atari_breakout
      - name: Create build directory and enter
        run: cd atari_breakout && mkdir build && cd build
      - name: Create cmake files
        run: cd atari_breakout\build && cmake ..
      - name: Build
        run: cd atari_breakout\build && make
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: breakout